env: 'dev'
server:
  addr: localhost
  http_port: 8085
  ssl_port: 8086
  timeout: 4
  idle_timeout: 60
parser:
  classificator_name: import0_1.xml
  offer_name: offers0_1.xml
  imageFolder_name: import_files
  default_user_id: 1


